# Generated by Django 4.2.2 on 2023-06-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipios_ms',
            options={'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterField(
            model_name='municipios_ms',
            name='nm_mun',
            field=models.CharField(max_length=50, verbose_name='Nome Município'),
        ),
    ]
