# Generated by Django 4.2.2 on 2023-06-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shapefile',
        ),
    ]
