# Generated by Django 4.2.2 on 2023-06-07 12:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codlote', models.CharField(blank=True, max_length=11, null=True)),
                ('codelote', models.CharField(blank=True, max_length=11, null=True)),
                ('inscant', models.CharField(blank=True, max_length=11, null=True)),
                ('tipoloc', models.CharField(blank=True, max_length=10, null=True)),
                ('ruaimo', models.CharField(blank=True, max_length=50, null=True)),
                ('nrporta', models.BigIntegerField(blank=True, null=True)),
                ('complement', models.CharField(blank=True, max_length=16, null=True)),
                ('parcelamen', models.CharField(blank=True, max_length=50, null=True)),
                ('patrimonio', models.CharField(blank=True, max_length=36, null=True)),
                ('usoimovel', models.CharField(blank=True, max_length=36, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_len', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=31981)),
            ],
        ),
    ]
