# Generated by Django 4.2.2 on 2023-06-07 14:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoImob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField(blank=True, null=True)),
                ('informante', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('parcelamen', models.CharField(blank=True, max_length=50, null=True)),
                ('testada', models.FloatField(blank=True, null=True)),
                ('areaterren', models.FloatField(blank=True, null=True)),
                ('preco', models.FloatField(blank=True, null=True)),
                ('quadra', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('inscant', models.CharField(blank=True, max_length=11, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('regiao', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.CharField(blank=True, max_length=50, null=True)),
                ('pavimentac', models.CharField(blank=True, max_length=1, null=True)),
                ('n_testadas', models.BigIntegerField(blank=True, null=True)),
                ('preco_un', models.FloatField(blank=True, null=True)),
                ('contato_in', models.CharField(blank=True, max_length=50, null=True)),
                ('formatoter', models.CharField(blank=True, max_length=10, null=True)),
                ('topografia', models.BigIntegerField(blank=True, null=True)),
                ('fat_fonte', models.CharField(blank=True, max_length=1, null=True)),
                ('indice', models.FloatField(blank=True, null=True)),
                ('created_us', models.CharField(blank=True, max_length=254, null=True)),
                ('created_da', models.DateField(blank=True, null=True)),
                ('last_edite', models.CharField(blank=True, max_length=254, null=True)),
                ('last_edi_1', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=31981)),
            ],
        ),
    ]
