# Generated by Django 4.2.2 on 2023-06-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacaoimob',
            options={'ordering': ['-objectid'], 'verbose_name': 'Avaliação Imobiliária', 'verbose_name_plural': 'Avaliações Imobiliárias'},
        ),
    ]
